### ISSUE TITLE
can't find config.ini file in both folders of webstorage and mysql despite running the run-steps.py file

### ISSUE THREAD

**Issue by Mudassiruddin7** [anikethchavare/Elvvo#1]

**Comment by anikethchavare** [comment]
Hi @Mudassiruddin7,

I am currently fixing that bug and improving the overall user experience of the project by combining the **MySQL** and **Web Storage** database mechanisms. Users can select their preferred database mechanism after executing the **run-steps.py** file.

Previously, there were two separate web servers for each database mechanism, but there will be only one for both in the next update. Please keep an eye out for future updates.

Thanks,
Aniketh Chavare
